[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' https://cdn.matomo.cloud; img-src 'self' https://test-analytics.matomo.cloud;"